name: Helm package and push OCI image to GAR

permissions:
  contents: read
  id-token: write

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
    paths:
      - 'infra/go-demo-app/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'infra/go-demo-app/**'
  workflow_dispatch:

jobs:
  security-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Conftest
        run: |
          CONFTEST_VERSION="0.61.2"
          curl -L -o conftest.tar.gz "https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz"
          tar xzf conftest.tar.gz
          sudo mv conftest /usr/local/bin/conftest
          conftest --version

      - name: Validate Security Policies
        run: |
          helm template test-release infra/go-demo-app | conftest test --policy infra/policy -

  generate-build-id:
    needs: security-validation
    runs-on: ubuntu-latest
    outputs:
      CHART_VERSION: "v0.1.0-${{ steps.prep.outputs.BUILD_ID }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_OUTPUT

  package-and-push-helm-chart-to-gar:
    needs: generate-build-id
    uses: andreistefanciprian/gh-reusable-workflows/.github/workflows/build_and_push_helm_chart_to_gar.yaml@main
    with:
      app_name: go-demo-app
      chart_version: ${{ needs.generate-build-id.outputs.CHART_VERSION }}
    secrets: inherit
